[toolchain]
profile = "minimal"
channel = "nightly-2025-07-01"
components = [
  "rust-src",
  "rustfmt",
  "clippy",
  "rust-analyzer",
  "llvm-tools-preview",
]
targets = [
  "riscv64imac-unknown-none-elf"
]
